import { prisma } from '@/lib/db';

let ensurePromise: Promise<boolean> | null = null;

const STATEMENTS: string[] = [
  `DO $$ BEGIN CREATE TYPE "AnnouncementCategory" AS ENUM ('ACADEMIC', 'DOCUMENTS', 'ADMINISTRATIVE', 'GROUP_WORK', 'UNIVERSITY_WIDE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE "AnnouncementPriority" AS ENUM ('INFORMATIONAL', 'IMPORTANT', 'URGENT', 'CRITICAL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN CREATE TYPE "AnnouncementSourceKind" AS ENUM ('MANUAL', 'EXAM', 'ASSIGNMENT', 'ATTENDANCE', 'DOCUMENT', 'SCHEDULE', 'CALENDAR', 'GROUP'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "preview" TEXT`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "priorityLevel" "AnnouncementPriority" DEFAULT 'INFORMATIONAL'`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "category" "AnnouncementCategory" DEFAULT 'ACADEMIC'`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "sourceKind" "AnnouncementSourceKind" DEFAULT 'MANUAL'`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "sourceRef" TEXT`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "linkHref" TEXT`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "linkLabel" TEXT`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "taggedUserIds" TEXT[] DEFAULT ARRAY[]::TEXT[]`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "taggedGroupIds" TEXT[] DEFAULT ARRAY[]::TEXT[]`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "pushNotify" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "SubjectAnnouncement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "SubjectAnnouncement_sourceRef_key" ON "SubjectAnnouncement"("sourceRef")`,
  `CREATE INDEX IF NOT EXISTS "SubjectAnnouncement_category_idx" ON "SubjectAnnouncement"("category")`,
  `CREATE INDEX IF NOT EXISTS "SubjectAnnouncement_priorityLevel_idx" ON "SubjectAnnouncement"("priorityLevel")`,
  `UPDATE "SubjectAnnouncement" SET "priorityLevel" = 'URGENT' WHERE "priority" = 'high' AND "priorityLevel" IS NULL`,
  `UPDATE "SubjectAnnouncement" SET "priorityLevel" = 'INFORMATIONAL' WHERE ("priorityLevel" IS NULL OR "priority" = 'normal')`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "preview" TEXT`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "priorityLevel" "AnnouncementPriority" DEFAULT 'IMPORTANT'`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "category" "AnnouncementCategory" DEFAULT 'UNIVERSITY_WIDE'`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "linkHref" TEXT`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "linkLabel" TEXT`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "pinned" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "attachments" JSONB`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "audienceFilter" JSONB`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "taggedUserIds" TEXT[] DEFAULT ARRAY[]::TEXT[]`,
  `ALTER TABLE "UniversityAnnouncement" ADD COLUMN IF NOT EXISTS "pushNotify" BOOLEAN NOT NULL DEFAULT true`,
  `CREATE TABLE IF NOT EXISTS "AnnouncementRead" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "subjectAnnouncementId" TEXT,
    "universityAnnouncementId" TEXT,
    "readAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AnnouncementRead_pkey" PRIMARY KEY ("id")
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "AnnouncementRead_userId_subjectAnnouncementId_key" ON "AnnouncementRead"("userId", "subjectAnnouncementId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "AnnouncementRead_userId_universityAnnouncementId_key" ON "AnnouncementRead"("userId", "universityAnnouncementId")`,
  `CREATE INDEX IF NOT EXISTS "AnnouncementRead_userId_readAt_idx" ON "AnnouncementRead"("userId", "readAt")`,
  `DO $$ BEGIN ALTER TABLE "AnnouncementRead" ADD CONSTRAINT "AnnouncementRead_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "AnnouncementRead" ADD CONSTRAINT "AnnouncementRead_subjectAnnouncementId_fkey" FOREIGN KEY ("subjectAnnouncementId") REFERENCES "SubjectAnnouncement"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `DO $$ BEGIN ALTER TABLE "AnnouncementRead" ADD CONSTRAINT "AnnouncementRead_universityAnnouncementId_fkey" FOREIGN KEY ("universityAnnouncementId") REFERENCES "UniversityAnnouncement"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
];

async function tableReady(): Promise<boolean> {
  try {
    await prisma.$queryRaw`SELECT 1 FROM "AnnouncementRead" LIMIT 1`;
    return true;
  } catch {
    return false;
  }
}

async function runEnsure(): Promise<boolean> {
  if (await tableReady()) return true;
  for (const sql of STATEMENTS) {
    try {
      await prisma.$executeRawUnsafe(sql);
    } catch (e) {
      console.error('[ensure-announcements-schema]', e);
    }
  }
  return tableReady();
}

export function ensureAnnouncementTables(): Promise<boolean> {
  if (!ensurePromise) {
    ensurePromise = runEnsure().then((ok) => {
      if (!ok) ensurePromise = null;
      return ok;
    });
  }
  return ensurePromise;
}
