import type {
  AnnouncementCategory,
  AnnouncementPriority,
  AnnouncementSourceKind,
} from '@prisma/client';
import { prisma } from '@/lib/db';
import { ensureAnnouncementTables } from '@/lib/db/ensure-announcements-schema';
import { assignmentSourceRef } from '@/lib/student/assignment-sync';
import { attendanceSessionSourceRef } from '@/lib/student/attendance-sync';
import { examSourceRef } from '@/lib/student/exam-sync';

export const announcementSourceRef = (kind: string, id: string) => `${kind}:${id}`;

export interface AutoAnnouncementInput {
  subjectId: string;
  authorId: string;
  sourceRef: string;
  sourceKind: AnnouncementSourceKind;
  category: AnnouncementCategory;
  priorityLevel: AnnouncementPriority;
  title: string;
  body: string;
  preview?: string;
  linkHref: string;
  linkLabel: string;
  pinned?: boolean;
  attachments?: unknown;
  pushNotify?: boolean;
}

async function enrolledStudentIds(subjectId: string): Promise<string[]> {
  const rows = await prisma.subjectEnrollment.findMany({
    where: { subjectId },
    select: { studentId: true },
  });
  return rows.map((r) => r.studentId);
}

export async function pushAnnouncementNotifications(
  studentIds: string[],
  params: {
    title: string;
    message: string;
    link: string;
    priorityLevel: AnnouncementPriority;
  }
): Promise<void> {
  const unique = [...new Set(studentIds)];
  if (unique.length === 0) return;

  await prisma.notification.createMany({
    data: unique.map((userId) => ({
      userId,
      type: 'ANNOUNCEMENT' as const,
      title: params.title,
      message: params.message,
      link: params.link,
    })),
    skipDuplicates: false,
  });
}

export async function upsertSubjectAutoAnnouncement(
  input: AutoAnnouncementInput
): Promise<string | null> {
  const ready = await ensureAnnouncementTables();
  if (!ready) return null;

  const publishedAt = new Date();
  const legacyPriority =
    input.priorityLevel === 'CRITICAL' || input.priorityLevel === 'URGENT'
      ? 'high'
      : 'normal';

  const existing = await prisma.subjectAnnouncement.findUnique({
    where: { sourceRef: input.sourceRef },
  });

  const data = {
    subjectId: input.subjectId,
    authorId: input.authorId,
    title: input.title,
    body: input.body,
    preview: input.preview ?? input.body.slice(0, 200),
    priority: legacyPriority,
    priorityLevel: input.priorityLevel,
    category: input.category,
    sourceKind: input.sourceKind,
    sourceRef: input.sourceRef,
    linkHref: input.linkHref,
    linkLabel: input.linkLabel,
    pinned: input.pinned ?? input.priorityLevel === 'CRITICAL',
    attachments: input.attachments ?? undefined,
    isAutoGenerated: true,
    pushNotify: input.pushNotify ?? true,
    publishedAt,
  };

  const row = existing
    ? await prisma.subjectAnnouncement.update({ where: { id: existing.id }, data })
    : await prisma.subjectAnnouncement.create({ data });

  if (input.pushNotify !== false) {
    const students = await enrolledStudentIds(input.subjectId);
    const tagged = input as AutoAnnouncementInput & { taggedUserIds?: string[] };
    const targets =
      tagged.taggedUserIds && tagged.taggedUserIds.length > 0
        ? students.filter((id) => tagged.taggedUserIds!.includes(id))
        : students;

    await pushAnnouncementNotifications(targets, {
      title: input.title,
      message: input.preview ?? input.body.slice(0, 120),
      link: input.linkHref,
      priorityLevel: input.priorityLevel,
    });
  }

  return row.id;
}

export async function removeAutoAnnouncement(sourceRef: string): Promise<void> {
  await prisma.subjectAnnouncement.deleteMany({ where: { sourceRef } }).catch(() => {});
}

export async function syncExamAnnouncement(examId: string): Promise<void> {
  const exam = await prisma.exam.findUnique({
    where: { id: examId },
    include: {
      subject: { include: { teacher: { select: { userId: true } } } },
    },
  });
  if (!exam?.subjectId || !exam.subject) return;

  const authorId =
    exam.createdById ?? exam.subject.teacher?.userId ?? (await fallbackAuthor(exam.subjectId));
  if (!authorId) return;

  const dateStr = exam.date.toLocaleDateString('en-GB', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  const location = [exam.building, exam.room, exam.location].filter(Boolean).join(' · ');
  const daysUntil = (exam.date.getTime() - Date.now()) / 86400000;
  const priorityLevel: AnnouncementPriority =
    daysUntil <= 1 ? 'URGENT' : daysUntil <= 3 ? 'IMPORTANT' : 'INFORMATIONAL';

  await upsertSubjectAutoAnnouncement({
    subjectId: exam.subjectId,
    authorId,
    sourceRef: announcementSourceRef('exam', examId),
    sourceKind: 'EXAM',
    category: 'ACADEMIC',
    priorityLevel,
    title: `Exam update: ${exam.title}`,
    body: `Scheduled for ${dateStr}${location ? ` · ${location}` : ''}.${exam.onlineUrl ? ` Online: ${exam.onlineUrl}` : ''}`,
    preview: `Exam on ${dateStr}`,
    linkHref: `/student/academics/exams?exam=${examId}`,
    linkLabel: 'Open Exam',
    pushNotify: priorityLevel !== 'INFORMATIONAL',
  });
}

export async function syncAssignmentAnnouncement(assignmentId: string): Promise<void> {
  const assignment = await prisma.assignment.findUnique({
    where: { id: assignmentId },
    include: { subject: { include: { teacher: { select: { userId: true } } } } },
  });
  if (!assignment?.subject) return;

  const authorId =
    assignment.createdById ??
    assignment.subject.teacher?.userId ??
    (await fallbackAuthor(assignment.subjectId));
  if (!authorId) return;

  const due = assignment.dueDate.toLocaleDateString('en-GB', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  });
  const hoursUntil = (assignment.dueDate.getTime() - Date.now()) / 3600000;
  const priorityLevel: AnnouncementPriority =
    hoursUntil <= 24 ? 'URGENT' : hoursUntil <= 72 ? 'IMPORTANT' : 'INFORMATIONAL';

  await upsertSubjectAutoAnnouncement({
    subjectId: assignment.subjectId,
    authorId,
    sourceRef: announcementSourceRef('assignment', assignmentId),
    sourceKind: 'ASSIGNMENT',
    category: 'ACADEMIC',
    priorityLevel,
    title: `Assignment: ${assignment.title}`,
    body: `Due ${due}. ${assignment.description?.slice(0, 300) ?? 'Open the assignment workspace for full details.'}`,
    preview: `Due ${due}`,
    linkHref: `/student/academics/assignments?assignment=${assignmentId}`,
    linkLabel: 'Open Assignment',
    pushNotify: hoursUntil <= 48,
  });
}

export async function syncDocumentAnnouncement(itemId: string): Promise<void> {
  const item = await prisma.subjectContentItem.findUnique({
    where: { id: itemId },
    include: {
      week: {
        include: {
          subject: { include: { teacher: { select: { userId: true } } } },
        },
      },
    },
  });
  if (!item?.week?.subject) return;

  const subject = item.week.subject;
  const authorId = subject.teacher?.userId ?? (await fallbackAuthor(subject.id));
  if (!authorId) return;

  await upsertSubjectAutoAnnouncement({
    subjectId: subject.id,
    authorId,
    sourceRef: announcementSourceRef('document', itemId),
    sourceKind: 'DOCUMENT',
    category: 'DOCUMENTS',
    priorityLevel: item.examPriority ? 'IMPORTANT' : 'INFORMATIONAL',
    title: `New material: ${item.title}`,
    body: `${item.type} uploaded to ${item.week.title ?? `Week ${item.week.weekNumber}`}.`,
    preview: item.description?.slice(0, 160) ?? item.title,
    linkHref: `/student/academics/documents?highlight=${itemId}`,
    linkLabel: 'View in Documents',
    attachments: item.fileUrl || item.url ? [{ title: item.title, url: item.url, fileUrl: item.fileUrl }] : undefined,
  });
}

export async function syncAttendanceAnnouncement(sessionId: string): Promise<void> {
  const session = await prisma.subjectAttendanceSession.findUnique({
    where: { id: sessionId },
    include: { subject: { include: { teacher: { select: { userId: true } } } } },
  });
  if (!session) return;

  const authorId =
    session.subject.teacher?.userId ?? (await fallbackAuthor(session.subjectId));
  if (!authorId) return;

  const dateStr = (session.movedTo ?? session.date).toLocaleDateString('en-GB', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  });

  let title: string;
  let body: string;
  let priorityLevel: AnnouncementPriority = 'IMPORTANT';
  let category: AnnouncementCategory = 'ADMINISTRATIVE';

  if (session.canceled) {
    title = `Class canceled: ${session.label ?? session.subject.name}`;
    body = `The class on ${dateStr} has been canceled.`;
    priorityLevel = 'CRITICAL';
  } else if (session.movedTo) {
    title = `Class rescheduled: ${session.label ?? session.subject.name}`;
    body = `Moved to ${dateStr}.`;
    priorityLevel = 'URGENT';
  } else if (session.isOnline) {
    title = `Class now online: ${session.label ?? session.subject.name}`;
    body = `${dateStr} — this session will be held online.`;
    priorityLevel = 'URGENT';
  } else {
    title = `Attendance recorded: ${session.label ?? 'Class session'}`;
    body = `Attendance for ${dateStr} has been updated.`;
    category = 'ACADEMIC';
    priorityLevel = 'INFORMATIONAL';
  }

  await upsertSubjectAutoAnnouncement({
    subjectId: session.subjectId,
    authorId,
    sourceRef: announcementSourceRef('attendance', sessionId),
    sourceKind: 'ATTENDANCE',
    category,
    priorityLevel,
    title,
    body,
    preview: body,
    linkHref: '/student/academics/attendance',
    linkLabel: 'View Attendance',
    pinned: session.canceled,
    pushNotify: priorityLevel === 'CRITICAL' || priorityLevel === 'URGENT',
  });
}

export async function syncScheduleSlotAnnouncement(
  subjectId: string,
  change: 'room' | 'time' | 'cancel',
  details: { label?: string; room?: string; dayOfWeek?: number }
): Promise<void> {
  const subject = await prisma.subject.findUnique({
    where: { id: subjectId },
    include: { teacher: { select: { userId: true } } },
  });
  if (!subject) return;

  const authorId = subject.teacher?.userId ?? (await fallbackAuthor(subjectId));
  if (!authorId) return;

  const ref = announcementSourceRef('schedule', `${subjectId}:${change}:${details.dayOfWeek ?? 0}`);

  const titles = {
    room: `Room change: ${details.label ?? subject.name}`,
    time: `Schedule change: ${details.label ?? subject.name}`,
    cancel: `Class canceled: ${details.label ?? subject.name}`,
  };

  await upsertSubjectAutoAnnouncement({
    subjectId,
    authorId,
    sourceRef: ref,
    sourceKind: 'SCHEDULE',
    category: 'ADMINISTRATIVE',
    priorityLevel: change === 'cancel' ? 'CRITICAL' : 'URGENT',
    title: titles[change],
    body:
      change === 'room'
        ? `New room: ${details.room ?? 'TBA'}`
        : change === 'cancel'
          ? 'This recurring class slot has been canceled.'
          : 'Weekly schedule has been updated.',
    linkHref: '/student/academics/schedule',
    linkLabel: 'View Schedule',
    pinned: change === 'cancel',
    pushNotify: true,
  });
}

export async function broadcastUniversityAnnouncement(announcementId: string): Promise<void> {
  const ready = await ensureAnnouncementTables();
  if (!ready) return;

  const ann = await prisma.universityAnnouncement.findUnique({
    where: { id: announcementId },
  });
  if (!ann || ann.status !== 'SENT' || !ann.publishedAt) return;

  const filter = (ann.audienceFilter ?? {}) as {
    courseIds?: string[];
    yearLevels?: number[];
    departments?: string[];
  };

  const students = await prisma.studentProfile.findMany({
    where: {
      universityId: ann.universityId,
      ...(filter.courseIds?.length ? { courseId: { in: filter.courseIds } } : {}),
      ...(filter.yearLevels?.length ? { yearOfStudy: { in: filter.yearLevels } } : {}),
    },
    select: { userId: true },
  });

  let userIds = students.map((s) => s.userId);
  if (ann.taggedUserIds.length > 0) {
    userIds = userIds.filter((id) => ann.taggedUserIds.includes(id));
  }

  if (ann.pushNotify) {
    await pushAnnouncementNotifications(userIds, {
      title: ann.title,
      message: ann.preview ?? ann.message.slice(0, 120),
      link: ann.linkHref ?? '/student/academics/announcements',
      priorityLevel: ann.priorityLevel,
    });
  }
}

async function fallbackAuthor(subjectId: string): Promise<string | null> {
  const enrollment = await prisma.subjectEnrollment.findFirst({
    where: { subjectId },
    select: { studentId: true },
  });
  return enrollment?.studentId ?? null;
}

/** Re-export refs used when removing linked entities */
export { examSourceRef, assignmentSourceRef, attendanceSessionSourceRef };
