import type { ResourceHubCategory, ResourceScope } from '@prisma/client';

export interface CuratedResourceSeed {
  id: string;
  title: string;
  description: string;
  category: ResourceHubCategory;
  subcategory: string;
  scope: ResourceScope;
  url?: string;
  internalPath?: string;
  iconKey: string;
  tags: string[];
  keywords: string;
  isOfficial?: boolean;
  isTrending?: boolean;
  saveCount?: number;
  subjectTags?: string[];
}

export const CURATED_RESOURCES: CuratedResourceSeed[] = [
  {
    id: 'seed-career-cv-harvard',
    title: 'Harvard CV Guide',
    description: 'Professional CV structure and examples for students and graduates.',
    category: 'CAREER',
    subcategory: 'CV Templates',
    scope: 'EXTERNAL',
    url: 'https://careerservices.fas.harvard.edu/resources/create-a-strong-resume/',
    iconKey: 'file-text',
    tags: ['cv', 'resume', 'template'],
    keywords: 'cv resume template career',
    isTrending: true,
    saveCount: 420,
  },
  {
    id: 'seed-career-cv-canva',
    title: 'Canva CV Templates',
    description: 'Modern, editable CV templates — free tier available.',
    category: 'CAREER',
    subcategory: 'CV Templates',
    scope: 'EXTERNAL',
    url: 'https://www.canva.com/resumes/templates/',
    iconKey: 'palette',
    tags: ['cv', 'design', 'template'],
    keywords: 'canva cv design template',
    saveCount: 380,
  },
  {
    id: 'seed-career-linkedin',
    title: 'LinkedIn Profile Optimization',
    description: 'Checklist for headline, summary, experience, and skills.',
    category: 'CAREER',
    subcategory: 'LinkedIn',
    scope: 'EXTERNAL',
    url: 'https://www.linkedin.com/help/linkedin/answer/a522735',
    iconKey: 'linkedin',
    tags: ['linkedin', 'networking', 'profile'],
    keywords: 'linkedin optimization profile networking',
    isTrending: true,
    saveCount: 510,
  },
  {
    id: 'seed-career-interview-star',
    title: 'STAR Interview Method',
    description: 'Structure behavioral answers: Situation, Task, Action, Result.',
    category: 'CAREER',
    subcategory: 'Interview Prep',
    scope: 'EXTERNAL',
    url: 'https://www.themuse.com/advice/star-interview-method',
    iconKey: 'message-circle',
    tags: ['interview', 'behavioral'],
    keywords: 'interview star behavioral preparation',
    saveCount: 290,
  },
  {
    id: 'seed-career-intern-erasmus',
    title: 'Erasmus Intern',
    description: 'EU platform for internships and traineeships abroad.',
    category: 'CAREER',
    subcategory: 'Internships',
    scope: 'EXTERNAL',
    url: 'https://erasmusintern.org/',
    iconKey: 'globe',
    tags: ['internship', 'erasmus', 'abroad'],
    keywords: 'erasmus internship abroad europe',
    isOfficial: true,
    saveCount: 340,
  },
  {
    id: 'seed-career-intern-linkedin',
    title: 'LinkedIn Jobs & Internships',
    description: 'Search internships filtered by location and field.',
    category: 'CAREER',
    subcategory: 'Internships',
    scope: 'EXTERNAL',
    url: 'https://www.linkedin.com/jobs/internship-jobs',
    iconKey: 'briefcase',
    tags: ['internship', 'jobs'],
    keywords: 'linkedin jobs internship',
    saveCount: 260,
  },
  {
    id: 'seed-career-internal-compat',
    title: 'UniBridge Career Compatibility',
    description: 'Match your profile with career paths and opportunities.',
    category: 'CAREER',
    subcategory: 'Career Tools',
    scope: 'INTERNAL',
    internalPath: '/student/career/compatibility',
    iconKey: 'target',
    tags: ['career', 'unibridge'],
    keywords: 'career compatibility paths',
    saveCount: 180,
  },
  {
    id: 'seed-startup-pitch-ycombinator',
    title: 'Y Combinator Pitch Deck Guide',
    description: 'How to build a compelling startup pitch deck.',
    category: 'STARTUP',
    subcategory: 'Pitch Deck',
    scope: 'EXTERNAL',
    url: 'https://www.ycombinator.com/library/2u-how-to-build-your-seed-round-pitch-deck',
    iconKey: 'presentation',
    tags: ['pitch', 'deck', 'startup'],
    keywords: 'pitch deck ycombinator startup',
    isTrending: true,
    saveCount: 450,
  },
  {
    id: 'seed-startup-pitch-canva',
    title: 'Canva Pitch Deck Templates',
    description: 'Investor-ready slide templates for early-stage startups.',
    category: 'STARTUP',
    subcategory: 'Pitch Deck',
    scope: 'EXTERNAL',
    url: 'https://www.canva.com/presentations/templates/pitch-deck/',
    iconKey: 'palette',
    tags: ['pitch', 'design'],
    keywords: 'pitch deck canva template',
    saveCount: 320,
  },
  {
    id: 'seed-startup-research-statista',
    title: 'Statista Market Data',
    description: 'Statistics and market research for business cases.',
    category: 'STARTUP',
    subcategory: 'Market Research',
    scope: 'EXTERNAL',
    url: 'https://www.statista.com/',
    iconKey: 'bar-chart',
    tags: ['market', 'research', 'data'],
    keywords: 'market research statistics data',
    saveCount: 210,
  },
  {
    id: 'seed-startup-framework-bmc',
    title: 'Business Model Canvas',
    description: 'Visual framework to design and iterate your business model.',
    category: 'STARTUP',
    subcategory: 'Frameworks',
    scope: 'EXTERNAL',
    url: 'https://www.strategyzer.com/canvas/business-model-canvas',
    iconKey: 'layout-grid',
    tags: ['framework', 'business model'],
    keywords: 'business model canvas startup framework',
    isTrending: true,
    saveCount: 390,
  },
  {
    id: 'seed-startup-nocode-bubble',
    title: 'Bubble No-Code Builder',
    description: 'Build web apps without code — MVP prototyping.',
    category: 'STARTUP',
    subcategory: 'No-Code',
    scope: 'EXTERNAL',
    url: 'https://bubble.io/',
    iconKey: 'code',
    tags: ['no-code', 'mvp'],
    keywords: 'no-code bubble mvp prototype',
    saveCount: 275,
  },
  {
    id: 'seed-startup-internal-hub',
    title: 'UniBridge Startup Hub',
    description: 'Discover startups, teams, and innovation programs on campus.',
    category: 'STARTUP',
    subcategory: 'Campus Startup',
    scope: 'INTERNAL',
    internalPath: '/student/startup/discover',
    iconKey: 'rocket',
    tags: ['startup', 'unibridge'],
    keywords: 'startup discover incubator',
    saveCount: 195,
  },
  {
    id: 'seed-uni-library',
    title: 'University Digital Library',
    description: 'Access journals, ebooks, and academic databases.',
    category: 'UNIVERSITY',
    subcategory: 'Library',
    scope: 'EXTERNAL',
    url: 'https://scholar.google.com/',
    iconKey: 'book-open',
    tags: ['library', 'research', 'papers'],
    keywords: 'library journals research google scholar',
    isOfficial: true,
    saveCount: 600,
  },
  {
    id: 'seed-uni-regulations',
    title: 'Academic Regulations',
    description: 'Official rules on assessment, attendance, and progression.',
    category: 'UNIVERSITY',
    subcategory: 'Regulations',
    scope: 'INTERNAL',
    internalPath: '/student/academics/announcements',
    iconKey: 'scale',
    tags: ['regulations', 'official'],
    keywords: 'academic regulations rules assessment',
    isOfficial: true,
    saveCount: 220,
  },
  {
    id: 'seed-uni-erasmus',
    title: 'Erasmus+ Programme',
    description: 'Mobility, exchanges, and international study opportunities.',
    category: 'UNIVERSITY',
    subcategory: 'Erasmus',
    scope: 'EXTERNAL',
    url: 'https://erasmus-plus.ec.europa.eu/',
    iconKey: 'globe',
    tags: ['erasmus', 'mobility', 'exchange'],
    keywords: 'erasmus exchange mobility international',
    isOfficial: true,
    isTrending: true,
    saveCount: 480,
  },
  {
    id: 'seed-uni-support',
    title: 'Student Support Services',
    description: 'Counseling, wellbeing, and academic guidance contacts.',
    category: 'UNIVERSITY',
    subcategory: 'Support',
    scope: 'INTERNAL',
    internalPath: '/student/profile',
    iconKey: 'heart-handshake',
    tags: ['support', 'wellbeing'],
    keywords: 'student support counseling wellbeing',
    isOfficial: true,
    saveCount: 310,
  },
  {
    id: 'seed-uni-calendar',
    title: 'Academic Calendar',
    description: 'Key dates, exam periods, and university holidays.',
    category: 'UNIVERSITY',
    subcategory: 'Calendar',
    scope: 'INTERNAL',
    internalPath: '/student/academics/calendar',
    iconKey: 'calendar',
    tags: ['calendar', 'dates'],
    keywords: 'academic calendar holidays exams',
    isOfficial: true,
    saveCount: 540,
  },
  {
    id: 'seed-uni-scholarships',
    title: 'Scholarships & Funding',
    description: 'Financial aid, grants, and merit-based scholarships.',
    category: 'UNIVERSITY',
    subcategory: 'Scholarships',
    scope: 'EXTERNAL',
    url: 'https://www.scholarships.com/',
    iconKey: 'graduation-cap',
    tags: ['scholarship', 'funding'],
    keywords: 'scholarship funding financial aid',
    isOfficial: true,
    saveCount: 350,
  },
  {
    id: 'seed-uni-campus-map',
    title: 'Campus Maps',
    description: 'Find buildings, labs, and services on campus.',
    category: 'UNIVERSITY',
    subcategory: 'Campus',
    scope: 'EXTERNAL',
    url: 'https://www.openstreetmap.org/',
    iconKey: 'map-pin',
    tags: ['campus', 'map'],
    keywords: 'campus map buildings location',
    isOfficial: true,
    saveCount: 190,
  },
  {
    id: 'seed-subject-canva',
    title: 'Canva Design Studio',
    description: 'Templates for presentations, marketing visuals, and reports.',
    category: 'SUBJECT',
    subcategory: 'Design Tools',
    scope: 'EXTERNAL',
    url: 'https://www.canva.com/',
    iconKey: 'palette',
    tags: ['marketing', 'design', 'presentation'],
    keywords: 'canva marketing design template presentation',
    subjectTags: ['marketing', 'design', 'communication', 'advertising'],
    isTrending: true,
    saveCount: 470,
  },
  {
    id: 'seed-subject-case-hbr',
    title: 'HBR Case Study Method',
    description: 'Framework for analyzing business case studies.',
    category: 'SUBJECT',
    subcategory: 'Frameworks',
    scope: 'EXTERNAL',
    url: 'https://hbr.org/2013/10/the-case-study-method',
    iconKey: 'book-marked',
    tags: ['case study', 'business', 'analysis'],
    keywords: 'case study framework business analysis hbr',
    subjectTags: ['marketing', 'management', 'business', 'economics'],
    saveCount: 330,
  },
  {
    id: 'seed-subject-desmos',
    title: 'Desmos Graphing Calculator',
    description: 'Interactive graphs for calculus, algebra, and statistics.',
    category: 'SUBJECT',
    subcategory: 'Calculators',
    scope: 'EXTERNAL',
    url: 'https://www.desmos.com/calculator',
    iconKey: 'calculator',
    tags: ['calculus', 'math', 'graphing'],
    keywords: 'desmos calculator graph calculus math',
    subjectTags: ['calculus', 'math', 'mathematics', 'algebra', 'statistics'],
    isTrending: true,
    saveCount: 520,
  },
  {
    id: 'seed-subject-wolfram',
    title: 'Wolfram Alpha',
    description: 'Step-by-step math, science, and engineering computations.',
    category: 'SUBJECT',
    subcategory: 'Calculators',
    scope: 'EXTERNAL',
    url: 'https://www.wolframalpha.com/',
    iconKey: 'sigma',
    tags: ['math', 'engineering', 'formula'],
    keywords: 'wolfram alpha math formula engineering',
    subjectTags: ['calculus', 'math', 'physics', 'engineering'],
    saveCount: 410,
  },
  {
    id: 'seed-subject-formulas',
    title: "Formula Sheets — Paul's Notes",
    description: 'Concise formula references for calculus and differential equations.',
    category: 'SUBJECT',
    subcategory: 'Reference',
    scope: 'EXTERNAL',
    url: 'https://tutorial.math.lamar.edu/',
    iconKey: 'file-text',
    tags: ['formula', 'calculus', 'reference'],
    keywords: 'formula sheet calculus reference notes',
    subjectTags: ['calculus', 'math', 'mathematics'],
    saveCount: 380,
  },
  {
    id: 'seed-subject-overleaf',
    title: 'Overleaf LaTeX Editor',
    description: 'Collaborative writing for thesis, papers, and lab reports.',
    category: 'SUBJECT',
    subcategory: 'Writing',
    scope: 'EXTERNAL',
    url: 'https://www.overleaf.com/',
    iconKey: 'pen-line',
    tags: ['latex', 'thesis', 'writing'],
    keywords: 'overleaf latex thesis paper writing',
    subjectTags: ['thesis', 'research', 'engineering', 'computer', 'physics'],
    saveCount: 290,
  },
  {
    id: 'seed-subject-internal-docs',
    title: 'Subject Documents Library',
    description: 'Lectures, workshops, and materials from your enrolled subjects.',
    category: 'SUBJECT',
    subcategory: 'Course Materials',
    scope: 'INTERNAL',
    internalPath: '/student/academics/documents',
    iconKey: 'folder-open',
    tags: ['documents', 'lectures'],
    keywords: 'documents lectures materials subject',
    subjectTags: [],
    saveCount: 440,
  },
  {
    id: 'seed-subject-internal-exams',
    title: 'Exam Command Center',
    description: 'Prep workspace linked to your subject exams and deadlines.',
    category: 'SUBJECT',
    subcategory: 'Exam Prep',
    scope: 'INTERNAL',
    internalPath: '/student/academics/exams',
    iconKey: 'notebook',
    tags: ['exams', 'study'],
    keywords: 'exams preparation study subject',
    subjectTags: [],
    saveCount: 360,
  },
  {
    id: 'seed-subject-internal-assignments',
    title: 'Assignments Workspace',
    description: 'Track, submit, and collaborate on subject assignments.',
    category: 'SUBJECT',
    subcategory: 'Assignments',
    scope: 'INTERNAL',
    internalPath: '/student/academics/assignments',
    iconKey: 'clipboard-list',
    tags: ['assignments', 'homework'],
    keywords: 'assignments homework submit subject',
    subjectTags: [],
    saveCount: 400,
  },
];

export const CATEGORY_LABELS: Record<ResourceHubCategory, string> = {
  CAREER: 'Career',
  STARTUP: 'Startup Hub',
  UNIVERSITY: 'University Resources',
  SUBJECT: 'Subject Tools',
};

export const CATEGORY_ORDER: ResourceHubCategory[] = [
  'CAREER',
  'STARTUP',
  'UNIVERSITY',
  'SUBJECT',
];
