import type { AnnouncementCategory, AnnouncementPriority } from '@prisma/client';
import { prisma } from '@/lib/db';
import { ensureAnnouncementTables } from '@/lib/db/ensure-announcements-schema';

export const CATEGORY_LABELS: Record<AnnouncementCategory, string> = {
  ACADEMIC: 'Academic',
  DOCUMENTS: 'Documents',
  ADMINISTRATIVE: 'Administrative',
  GROUP_WORK: 'Group Work',
  UNIVERSITY_WIDE: 'University',
};

export const PRIORITY_LABELS: Record<AnnouncementPriority, string> = {
  INFORMATIONAL: 'Informational',
  IMPORTANT: 'Important',
  URGENT: 'Urgent',
  CRITICAL: 'Critical',
};

export interface AnnouncementCard {
  id: string;
  kind: 'subject' | 'university';
  title: string;
  body: string;
  preview: string;
  category: AnnouncementCategory;
  priorityLevel: AnnouncementPriority;
  pinned: boolean;
  subjectId: string | null;
  subjectName: string | null;
  subjectCode: string | null;
  sourceName: string;
  sourceImage: string | null;
  professor: string | null;
  publishedAt: string;
  linkHref: string | null;
  linkLabel: string | null;
  attachments: { title: string; url?: string; fileUrl?: string }[];
  taggedUserIds: string[];
  isAutoGenerated: boolean;
  read: boolean;
  href: string;
}

export interface AnnouncementsHub {
  announcements: AnnouncementCard[];
  unreadCount: number;
  subjects: { id: string; name: string; code: string | null }[];
  professors: string[];
  dbReady: boolean;
  serverTime: string;
}

export interface AnnouncementFilters {
  subjectId?: string;
  category?: AnnouncementCategory;
  priorityLevel?: AnnouncementPriority;
  professor?: string;
  unreadOnly?: boolean;
  since?: string;
}

function parseAttachments(raw: unknown): AnnouncementCard['attachments'] {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((a) => a && typeof a === 'object')
    .map((a) => {
      const o = a as Record<string, string>;
      return { title: o.title ?? 'Attachment', url: o.url, fileUrl: o.fileUrl };
    });
}

export async function loadStudentAnnouncementsHub(
  studentId: string,
  filters: AnnouncementFilters = {}
): Promise<AnnouncementsHub> {
  const dbReady = await ensureAnnouncementTables();

  const enrollments = await prisma.subjectEnrollment.findMany({
    where: { studentId },
    include: {
      subject: {
        include: { teacher: { include: { user: { select: { name: true } } } } },
      },
    },
  });

  const active = enrollments.filter((e) => e.subject.status === 'ACTIVE');
  const subjectIds = active.map((e) => e.subjectId);

  const profile = await prisma.studentProfile.findUnique({
    where: { userId: studentId },
    select: { universityId: true },
  });

  const sinceDate = filters.since ? new Date(filters.since) : null;

  const [subjectRows, universityRows, reads] = await Promise.all([
    prisma.subjectAnnouncement.findMany({
      where: {
        subjectId: { in: subjectIds },
        ...(filters.subjectId ? { subjectId: filters.subjectId } : {}),
        ...(filters.category ? { category: filters.category } : {}),
        ...(filters.priorityLevel ? { priorityLevel: filters.priorityLevel } : {}),
        ...(sinceDate ? { updatedAt: { gt: sinceDate } } : {}),
        OR: [{ publishedAt: { not: null } }, { publishedAt: null, scheduledAt: null }],
      },
      include: {
        subject: { select: { id: true, name: true, code: true } },
        author: { select: { name: true, image: true } },
      },
      orderBy: [{ pinned: 'desc' }, { publishedAt: 'desc' }, { createdAt: 'desc' }],
      take: 120,
    }),
    profile?.universityId
      ? prisma.universityAnnouncement.findMany({
          where: {
            universityId: profile.universityId,
            status: 'SENT',
            publishedAt: { not: null },
            ...(filters.category === 'UNIVERSITY_WIDE' ? {} : {}),
            ...(sinceDate ? { updatedAt: { gt: sinceDate } } : {}),
          },
          orderBy: [{ pinned: 'desc' }, { publishedAt: 'desc' }],
          take: 40,
        })
      : Promise.resolve([]),
    dbReady
      ? prisma.announcementRead.findMany({
          where: { userId: studentId },
          select: { subjectAnnouncementId: true, universityAnnouncementId: true },
        })
      : Promise.resolve([]),
  ]);

  const readSubject = new Set(
    reads.map((r) => r.subjectAnnouncementId).filter(Boolean) as string[]
  );
  const readUniversity = new Set(
    reads.map((r) => r.universityAnnouncementId).filter(Boolean) as string[]
  );

  const professorBySubject = new Map(
    active.map((e) => [e.subjectId, e.subject.teacher?.user?.name ?? null])
  );

  let cards: AnnouncementCard[] = [
    ...subjectRows.map((a) => {
      const professor = professorBySubject.get(a.subjectId) ?? a.author.name;
      return {
        id: a.id,
        kind: 'subject' as const,
        title: a.title,
        body: a.body,
        preview: a.preview ?? a.body.slice(0, 200),
        category: a.category,
        priorityLevel: a.priorityLevel,
        pinned: a.pinned,
        subjectId: a.subject.id,
        subjectName: a.subject.name,
        subjectCode: a.subject.code,
        sourceName: a.author.name ?? 'Teacher',
        sourceImage: a.author.image,
        professor,
        publishedAt: (a.publishedAt ?? a.createdAt).toISOString(),
        linkHref: a.linkHref ?? `/student/academics/subjects/${a.subjectId}/announcements`,
        linkLabel: a.linkLabel ?? 'View Subject',
        attachments: parseAttachments(a.attachments),
        taggedUserIds: a.taggedUserIds,
        isAutoGenerated: a.isAutoGenerated,
        read: readSubject.has(a.id),
        href: `/student/academics/announcements?subject=${a.subjectId}`,
      };
    }),
    ...universityRows.map((a) => ({
      id: a.id,
      kind: 'university' as const,
      title: a.title,
      body: a.message,
      preview: a.preview ?? a.message.slice(0, 200),
      category: a.category,
      priorityLevel: a.priorityLevel,
      pinned: a.pinned,
      subjectId: null,
      subjectName: null,
      subjectCode: null,
      sourceName: 'University',
      sourceImage: null,
      professor: null,
      publishedAt: (a.publishedAt ?? a.createdAt).toISOString(),
      linkHref: a.linkHref ?? '/student/academics/announcements',
      linkLabel: a.linkLabel ?? 'View Details',
      attachments: parseAttachments(a.attachments),
      taggedUserIds: a.taggedUserIds,
      isAutoGenerated: false,
      read: readUniversity.has(a.id),
      href: '/student/academics/announcements',
    })),
  ];

  if (filters.professor) {
    const q = filters.professor.toLowerCase();
    cards = cards.filter((c) => c.professor?.toLowerCase().includes(q));
  }

  if (filters.unreadOnly) {
    cards = cards.filter((c) => !c.read);
  }

  cards.sort((a, b) => {
    if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
    const prio = { CRITICAL: 0, URGENT: 1, IMPORTANT: 2, INFORMATIONAL: 3 };
    const pd = prio[a.priorityLevel] - prio[b.priorityLevel];
    if (pd !== 0) return pd;
    return b.publishedAt.localeCompare(a.publishedAt);
  });

  const unreadCount = cards.filter((c) => !c.read).length;
  const professors = [
    ...new Set(cards.map((c) => c.professor).filter(Boolean) as string[]),
  ].sort();

  return {
    announcements: cards,
    unreadCount,
    subjects: active.map((e) => ({
      id: e.subject.id,
      name: e.subject.name,
      code: e.subject.code,
    })),
    professors,
    dbReady,
    serverTime: new Date().toISOString(),
  };
}

export async function markAnnouncementRead(
  userId: string,
  params: { kind: 'subject' | 'university'; id: string }
): Promise<void> {
  const ready = await ensureAnnouncementTables();
  if (!ready) return;

  if (params.kind === 'subject') {
    const existing = await prisma.announcementRead.findFirst({
      where: { userId, subjectAnnouncementId: params.id },
    });
    if (existing) {
      await prisma.announcementRead.update({
        where: { id: existing.id },
        data: { readAt: new Date() },
      });
    } else {
      await prisma.announcementRead.create({
        data: { userId, subjectAnnouncementId: params.id },
      });
    }
  } else {
    const existing = await prisma.announcementRead.findFirst({
      where: { userId, universityAnnouncementId: params.id },
    });
    if (existing) {
      await prisma.announcementRead.update({
        where: { id: existing.id },
        data: { readAt: new Date() },
      });
    } else {
      await prisma.announcementRead.create({
        data: { userId, universityAnnouncementId: params.id },
      });
    }
  }
}

export async function markAllAnnouncementsRead(userId: string): Promise<void> {
  const hub = await loadStudentAnnouncementsHub(userId);
  const ready = await ensureAnnouncementTables();
  if (!ready) return;

  for (const a of hub.announcements) {
    if (a.read) continue;
    await markAnnouncementRead(userId, {
      kind: a.kind,
      id: a.id,
    });
  }
}

export async function getTeacherAnnouncementAnalytics(subjectId: string) {
  const announcements = await prisma.subjectAnnouncement.findMany({
    where: { subjectId, publishedAt: { not: null } },
    include: {
      reads: { select: { userId: true, readAt: true } },
    },
    orderBy: { publishedAt: 'desc' },
    take: 30,
  });

  const enrollments = await prisma.subjectEnrollment.count({ where: { subjectId } });

  return announcements.map((a) => ({
    id: a.id,
    title: a.title,
    publishedAt: a.publishedAt?.toISOString(),
    priorityLevel: a.priorityLevel,
    category: a.category,
    viewCount: a.reads.length,
    unreadPercent:
      enrollments > 0
        ? Math.round(((enrollments - a.reads.length) / enrollments) * 100)
        : 0,
    engagementPercent:
      enrollments > 0 ? Math.round((a.reads.length / enrollments) * 100) : 0,
  }));
}
